import React from "react";
import Watchlist from "@/components/ui/WatchList/WatchList";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: " Watchlist | Movie App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Watchlist />
    </>
  );
};

export default page;
