import LoginForm from "@/components/ui/login/Login";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function page() {
  return <LoginForm />;
}
