import MovieCredit from "@/components/ui/movieDetails/MovieCredit";
import MovieDetails from "@/components/ui/movieDetails/MovieDetails";
import MovieRecommandation from "@/components/ui/movieDetails/MovieRecommandation";
import { fetchMovieDetails } from "@/config/fetcher";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: " Movie Details | Movie App",
  description: "Generated by create next app",
};

async function MovieDetailsPage({ params }: { params: any }) {
  const { id } = await params;

  const movieData = await fetchMovieDetails(`/movie/${id}`);

  const castData = await fetchMovieDetails(`/movie/${id}/credits`);

  const recommendationsData = await fetchMovieDetails(
    `/movie/${id}/recommendations`
  );

  return (
    <>
      <MovieDetails data={movieData} />

      {/* Cast List */}
      <MovieCredit data={castData} />

      {/* Recommendations */}
      <MovieRecommandation data={recommendationsData?.results} />
    </>
  );
}

export default MovieDetailsPage;

export const dynamicParams = true;
export const revalidate = 60; // Revalidate the page every 60 seconds
